### ISSUE TITLE
Permission needed to read and change data in Firefox 109.0 (64-bit) och MacOS

### ISSUE THREAD

**Issue by panomitrius** [yorkxin/copy-as-markdown#116]
## Summary

I can't use the plugin on latest Firefox 109.0 (64-bit) on MacOS Ventura (M1)

## Reproduction Steps

1. Installing the plugin, granting basic permissions

## Expected Behavior

- Being able to use the plugin

## Actual Behavior

- Can't use the plugin

## Reproducible Environment

- Browser (Version):Firefox 109.0 (64-bit)
- Operating System (Version):MacOS Ventura 13.1 (22C65)
- System Language: English / Swedish
- Example Webpage (if applicable): Github

**Comment by yorkxin** [comment]
Thanks for the update. I am sometimes confused by the UI too. It seems that Firefox finally implemented a restriction to extension permissions that 'only allows it to read website data when clicking the icon'. I'll take a closer look to this issue and see if there is anything I can do to dismiss the warning.
