### ISSUE TITLE
shortcut not work under Chrome, works under firefox

### ISSUE THREAD

**Issue by jiewangjs** [yorkxin/copy-as-markdown#118]
I don't the reason, this is what I found after testing. 
If possible, please fix chrome's shortcut mechanism. 
Thanks !

**Comment by yorkxin** [comment]
I am able to use shortcuts on Chrome 110 on macOS 13.2.1. Could you give me some information about the version of Chrome and the operating system you are using?

Not sure if related but please also tell me the website you are trying to run the shortcut command, if possible.

Thanks!

p.s. if you are more comfortable using Chinese then please 您可以用中文回覆。

**Comment by jiewangjs** [comment]
Many thanks, I just tried on Chrome under my Windows OS, it all works now. 




|
|


|

**Comment by yorkxin** [comment]
Thanks for the update, @jiewangjs
