### ISSUE TITLE
Generated link title contains reserved characters (Brackets) in version 2.7.1

### ISSUE THREAD

**Issue by dank8** [yorkxin/copy-as-markdown#121]
## Summary
Tiles with brackets currently break the markdown coded link. Please sanitize the Title text to remove square brackets.

## Reproduction Steps
1. Open the example webpage 
1. click "copy as markdown" toolbar button.

_Tested with the following options:_
- Current Tab Link
- All Tab links
- All Tab titles

## Expected Behavior
generated text is a valid markdown link
```lang-md
[Example title 2023 Asana](https://asana.com/resources/)
```

**Optional request:** can the hostname be added to the link title. example:
- [7 Types of Process Improvement Methodologies 2023 Asana (asana.com)](https://asana.com/resources/process-improvement-methodologies)

## Actual Behavior
generated link text includes square brackets, breaking the markdown link format
```lang-md
[7 Types of ... [2023] • Asana](https://asana.com/resources/)
```

## Reproducible Environment
- Firefox Add-on: copy as markdown; Version 2.7.1; Last Updated April 27, 2023
- Browser (Version): Firefox 109.0.1 (64-bit)
- Operating System (Version): Linux; Linux alpinelinux 5.15.108-0-lts # 1-Alpine SMP Fri, 21 Apr 2023 05:55:14 +0000 x86_64 Linux
- System Language: en_AU
- Example Webpage (if applicable): https://asana.com/resources/process-improvement-methodologies

**Comment by dank8** [comment]
escaping reserved characters appears to be coded but not yet released. Cant find the issue number.

My other suggestion to add the hostname at the end of the link title. Here is modified version of function `Markdown.linkTo()` demonstrating an option (free for use):

```lang-js
function  linkTo(title, url) {
    let titleToUse;
    if (title === '') {
      titleToUse = this.constructor.DefaultTitle();
    } else {
      var hostName = '';
      try{ hostName = ' (' + url.split(/[\/\\]+/g)[1].replace(/^www\./g,'') + ')'; 
      } catch {}
      titleToUse = title + hostName;//this.escapeLinkText(title + hostName );
    }
    return `[${titleToUse}](${url})`;
  }

//some simple assertions
var result;

result = linkTo('hello world [1] all', 'https://helloworld.com/hellomonkey') === '[hello world [1] all (helloworld.com)](https://helloworld.com/hellomonkey)';
console.log( result );

result = linkTo('hello world [2] all', 'https://www.helloworld.com/hellomonkey') === '[hello world [2] all (helloworld.com)](https://www.helloworld.com/hellomonkey)';
console.log( result );

result = linkTo('hello world [3] all', 'file:///tmp/basic.htm') === '[hello world [3] all (tmp)](file:///tmp/basic.htm)';
console.log( result );
```

**Comment by yorkxin** [comment]
Sorry, just noticed this issue post. Most Markdown processors handle nested `[]`s correctly. If your processor does not handle it properly, please turn on "always escape" in the Options page of Copy as Markdown (under Advanced section), so that it will always escape brackets in the link title. Let me know if you still run into this trouble when using this option. Thanks!
