### ISSUE TITLE
Copy Chrome tab groups

### ISSUE THREAD

**Issue by NomarCub** [yorkxin/copy-as-markdown#123]
[Chrome tab groups](https://blog.google/products/chrome/manage-tabs-with-google-chrome/) provide some nice organization. They could be exported something like this with a sub list hierarchy:

```md
* group name
    * [link](url)
    * [link2](url)
* other group name
    * [link](url)
    * [link](url)
```

or alternatively with headings:

```md
# group name

* [link](url)
* [link2](url)

# other group name

* [link](url)
* [link](url)
```

There are plugins that already access tab groups, like [Save Tabs](https://github.com/Karna98/Save-Tabs), so there's probably some API you could use.

**Comment by yorkxin** [comment]
Thanks for the suggestion. Indeed there are APIs available: https://developer.chrome.com/docs/extensions/reference/api/tabGroups

**Comment by yorkxin** [comment]
Hi @NomarCub , as of version 2.16.0, "Copy Tabs as X" will now be wrapped in groups when they exist. Please try it out!

**Comment by NomarCub** [comment]
It works well, thank you!
