### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by jaxvanyang** [yorkxin/copy-as-markdown#124]
## Summary

Hi, this extension does exactly what I want. Thanks for your awesome work. But there is a little issue to me.

I use dark mode all the time, so I want to use this extension with a dark theme. This extension only has a white background menu. I think it would be better if it supports automatic theme switch. Or provide a option for changing the theme.

## Reproduction Steps

1. Click this extension menu.

## Expected Behavior

- Suit the website theme.

## Actual Behavior

- White backgound in dark site:
  ![image](https://github.com/yorkxin/copy-as-markdown/assets/25650612/0475dd07-39cb-4a8f-9a60-7e87ccd37183)

## Reproducible Environment

- Browser (Version): any
- Operating System (Version): any
- System Language: any
- Example Webpage (if applicable): any

**Comment by yorkxin** [comment]
Hi there, Dark Mode is available in version 2.12.0. Please check it out!

**Comment by jaxvanyang** [comment]
> Hi there, Dark Mode is available in version 2.12.0. Please check it out!

Just checked it on Firefox, thank you :+1:
