### ISSUE TITLE
Reduce permissions

### ISSUE THREAD

**Issue by yorkxin** [yorkxin/copy-as-markdown#148]
## Summary

After released #123 , I observed many uninstall events on Chrome Web Store. Some users reported that they are prompted for "accessing browsing history" permission, and believing this extension is doing something bad.

For context, the permission warning is from `tabs` permission, which has been there for a very long time. The permission warning was triggered because an additional `tabGroups` permission was requested as required.

Regardless, it is a best practice to not ask for too many permissions so that we don't scare users unnecessarily. When implementing Bookmarks integration  #146 , I made `bookmarks` an optional feature, so that the user can have more control about what data to expose to the extension.

**Comment by ezzatron** [comment]
Hey, I just got this scary-looking request from version `24.6.30`:

<img width="321" alt="Screenshot 2024-07-02 at 17 21 16" src="https://github.com/yorkxin/copy-as-markdown/assets/100152/8bec92d8-f282-41f1-89f9-3939c052725d">

I didn't really expect that this extension would need write permissions of any kind, so it definitely made me want to double-check what's going on.

**Comment by yorkxin** [comment]
@ezzatron Hi, thanks for sharing, this is definitely scaring. However I don't find the version number match the one I have released. The current latest version is `3.0.0` on Chrome. Could you take a screenshot of Extensions page on Chrome? Thanks.

**Comment by yorkxin** [comment]
@ezzatron Hi, I think you are talking about this extension: https://github.com/notlmn/copy-as-markdown

It just happened to have the same name as my extension. Please kindly contact their developer for your concern. Thanks!

**Comment by ezzatron** [comment]
Ah, sorry. My mistake!
