### ISSUE TITLE
Doesn't copy in Firefox Android

### ISSUE THREAD

**Issue by stevenxxiu** [yorkxin/copy-as-markdown#159]
## Summary
Clicking `Current tab link` does nothing.

It sees no tabs in the window, saying `All tabs link (0)`.

This did work in *Kiwi Browser*. I'm migrating to *Firefox*, so it'll be really appreciated if you can get this to work. This is the extension I use the most.

## Reproducible Environment

- Browser (Version): *Firefox Nightly* 132.0a1
- Operating System (Version): *Android* 14
- System Language: English
- Example Webpage (if applicable):

**Comment by yorkxin** [comment]
Hi,

Thanks for report. This extension has never been tested on Firefox on Android. As a matter of fact, I have never listed this extension with compatibility of Firefox on Android on the Mozilla Add-Ons listing.

As far as I know, Kiwi Browser is Chromium-based, which is probably why Chrome extensions happen to work on it. There are various different behaviors between Chromium-based browsers and Gecko-based browsers (Firefox), even on desktop environments, not to mention mobile environments. As an indie browser extension developer, there is a limit of how much devices I can support. Therefore, I have no play to support and has no plan to support Firefox in the foreseeable future.

I'll close this issue for now.
