### ISSUE TITLE
Copying the selection via right-click or toolbar button does not work

### ISSUE THREAD

**Issue by Poikilos** [yorkxin/copy-as-markdown#82]
## Summary

Copying the selection via right-click or toolbar button does not work.

## Reproduction Steps

![image](https://user-images.githubusercontent.com/7557867/76694403-bb0b9b80-6648-11ea-9cd2-961d67326c2e.png)

(or right-click on a selection)

## Expected Behavior

Copy to selection or other options should be available for the addon to function as described at the [page for the Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/copy-as-markdown): "Copy Links, Tabs & Images as Markdown via right clicks." though the statement is ambiguous, I suppose: it only copies those things individually, which is not very helpful.

## Actual Behavior

You can only copy one thing at a time, and the right-click menu item doesn't even appear if you right-click on a selection. 

## Reproducible Environment

- Browser (Version): Firefox 73.0.1
- Operating System (Version): Fedora 31
- System Language: English
- Example Webpage (if applicable): <https://start.fedoraproject.org/>

**Comment by llinfeng** [comment]
The following item from the right-click menu does get me to copy one hyperlink at a time. The following menu item also exist when I select a chunk of texts (hyper-linked) that contains multiple links. For now, I think `Copy [Link Concent](URL)` does what it described: to deal with one link at a time.

![image](https://user-images.githubusercontent.com/5890407/80594385-e24bdb80-89f0-11ea-9cb3-53af144daac3.png)

For example, on this [Graphviz Doc page](https://www.graphviz.org/documentation/), selecting a list of hyperlinks and clicking `Copy [Link Concent](URL)` only get all the texts into the square-bracket, leaving only the link for the first item in the parentheses.l

It would be more help if `Copy [Link Concent](URL)` can handle multiple hyperlinks as well. Also, it would also be helpful if such function can be assigned to a shortcut. For now, all shortcuts are about tab(s) operation.
