### ISSUE TITLE
Feature Request: Open new tabs from a list of links/URLs

### ISSUE THREAD

**Issue by cruscio** [yorkxin/copy-as-markdown#91]
## Feature Request

Please consider adding a mechanism to paste a markdown list of links or raw URLs, and open those URLs in the current window.

I often paste a list of tabs into documentation/ticketing/communication systems using _selected tabs link_, and then later want to reopen those tabs when revisiting a project. It would be nice to have a native way to do so.

**Comment by yorkxin** [comment]
Thanks for your suggestion. This feature is useful but doesn't fit into the domain of this extension. I would suggest you to build an extension for that feature yourself :)
