### ISSUE TITLE
[Feature Request] Copy as footnote

### ISSUE THREAD

**Issue by cruscio** [yorkxin/copy-as-markdown#92]
## Summary

Random thought - it'd be nice to have a menu option to copy a footnote format (e.g. [Hacker News style](https://news.ycombinator.com/item?id=24037026))
I often paste the output of `selected tabs link` somewhere (usually a list of search results to reference in an instruction or a request) and manually copy/convert the markdown list into something like this:

> [...] 
> replace that copy in the example with some lorum ipsum [[1](https://www.lipsum.com/)][[2](https://loremipsum.io/)][[3](https://loremipsum.io/generator/)] 
>
> [...]
>   
> * [Lorem Ipsum - All the facts - Lipsum generator](https://www.lipsum.com/)
> * [Lorem Ipsum – Generator, Origins and Meaning](https://loremipsum.io/)
> * [Lorem Ipsum Generator](https://loremipsum.io/generator/)
> 

It'd be nice to have basically the same as the `[All|Selected] tabs link` options, with a single line at the top containing a numbered set of links in brackets or braces or some such, to match the generated list. Then you could paste the whole thing at the bottom of a communication and cut/paste the numbered list into the appropriate anchor location within the written content above.

**Comment by yorkxin** [comment]
Hi, in version 3.1.0, custom format is introduced. Please try it out!

For your reference, here is an example template for reference links commonly used on Hacker News:

https://github.com/yorkxin/copy-as-markdown/wiki/Custom-Format-Examples#simple-texts
