### ISSUE TITLE
Feature request: Change Markdown bullet list character

### ISSUE THREAD

**Issue by pauljacobson** [yorkxin/copy-as-markdown#98]
## Summary

Currently the add-on formats the bullet list character (apologies, there's probably a better term for this, I'm going blank) using a `*`. For example:

```
* [Google Testing Blog: Test first is fun!](https://testing.googleblog.com/2008/09/test-first-is-fun_08.html)
* [What is Exploratory Testing? Techniques with Examples](https://www.guru99.com/exploratory-testing.html)
```

I'd love to be able to change this to a `-` as I prefer to format Markdown lists with a `-` instead of a `*`. Like this:

```
- [Google Testing Blog: Test first is fun!](https://testing.googleblog.com/2008/09/test-first-is-fun_08.html)
- [What is Exploratory Testing? Techniques with Examples](https://www.guru99.com/exploratory-testing.html)
```

## Reproducible Environment

- Browser (Version): Cross-browser
- Operating System (Version): macOS 11.6
- System Language: English
- Example Webpage (if applicable): Not applicable

**Comment by sorenpeter** [comment]
+1 for this one too.

I would also like to see an option to just use this syntax instead: `- Title: URL`

**Comment by jurassicparkin** [comment]
Hi, Thanks for the extension, I use it all the time in my workflow with Obsidian.

I'd also love an option in the settings to use a dash ( - ) for bullet points instead of an asterisk ( * )

Thanks!

**Comment by jurassicparkin** [comment]
> Sorry for keeping you waiting. This change has been shipped to Chrome Web Store, Edge Add-Ons and Firefox Add-Ons! You can find the option on the extension's options page in the browser.

Amazing! Thank you!

**Comment by sorenpeter** [comment]
Thanks you 🙏
